version: "2"
services:
  jenkins:
      image: jenkinsci/blueocean:2.263.2
      restart: always
      container_name: kinth_jenkins
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        - /home/kinth/jenkins/data:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /etc/localtime:/etc/localtime